export default [
    {
        languageOptions: {
            ecmaVersion: "latest",
            sourceType: "script",
            globals: {
                document: "readonly",
                window: "readonly",
                console: "readonly",
                alert: "readonly",
                prompt: "readonly",
                confirm: "readonly",
                Number: "readonly",
                String: "readonly",
                Boolean: "readonly",
                parseInt: "readonly",
                parseFloat: "readonly",
                JSON: "readonly",
                Math: "readonly",
                Date: "readonly",
                setInterval: "readonly",
                setTimeout: "readonly",
                location: "readonly",
                navigator: "readonly",
                localStorage: "readonly",
                fetch: "readonly",
            },
        },
        rules: {
            semi: ["error", "always"],
            quotes: ["error", "single"],
            "no-unused-vars": "error",
            "no-undef": "error",
            eqeqeq: ["error", "always"],
            "no-console": "off",
        },
    },
];